version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: mini-saas-tracker-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://backend:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend


  db:
    image: postgres:15
    container_name: mini-saas-tracker-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7
    container_name: mini-saas-tracker-redis-1
    ports:
      - "6379:6379"

volumes:
  postgres_data:
