# Generated by Django 5.2.4 on 2025-07-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('date', 'status')},
            },
        ),
    ]
